--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VennDev/TestVForm
build-by-default: true
branches:
- main
projects:
  TestVForm:
    path: ""
    libs:
      - src: VennDev/VFormOOPAPI/VFormOOPAPI
        version: ^2.2.3
        branch: "main"
      - src: VennDev/LibVapmPMMP/LibVapmPMMP
        version: ^1.8.8
        branch: "main"
...
